### ISSUE TITLE
Incorrect ROS Launch Command in Documentation

### ISSUE THREAD

**Issue by JJQ7** [ethz-asl/rio#10]
Hello @rikba 

I noticed a discrepancy in the documentation regarding the ROS launch command for the `rio` package. The Markdown file specifies the command as:
```
roslaunch rio rio.launch visualization:=true
```
However, according to the argument definition in `rio.launch`, the correct parameter should be `visualize:=true`. Using `visualization:=true` as stated in the documentation does not have any effect since it is not a recognized parameter.

Could you please update the documentation to reflect the correct command? This will help ensure that future users do not encounter the same issue.

Thank you for your attention to this matter.

**Comment by rikba** [comment]
Thanks for pointing it out.
