### ISSUE TITLE
advantages and differences of these two algorithms

### ISSUE THREAD

**Issue by anning808** [ethz-asl/rio#13]
This is the work that looks very amazing, I want to use this for my own work, I am now using an improved version of fastlio2, there are people who have used these two algorithms, tell me the advantages and differences of these two algorithms, I am very much looking forward to someone can tell me.

**Comment by rikba** [comment]
FastLIO2 is a lidar-inertial odometry (LIO) algorithm. It uses lidar to build a point cloud map and localize objects within this map, as well as calculate position, velocity, and orientation.

Our radar-inertial odometry algorithm uses radar. It does not build a dense map and only calculates the robot's position, velocity, and orientation.

So, LIO uses more expensive, heavy hardware, computation, and tuning to fit your environment's mapping parameters. However, it will give less drift, and you will get a dense point cloud from the lidar.

RIO does not do point cloud matching but immediately infers the drone velocity from the radar Doppler velocities. So, it's much easier to tune to different environments and computationally and weightwise lighter.

If you need an odometry solution for control, like stabilizing a drone, and you have some other source of global positioning for navigation, such as sparse GPS readings or some low-frequency SLAM solution, I would suggest a RIO solution.
