### ISSUE TITLE
Unable to Download Dataset - Possible Region Restriction

### ISSUE THREAD

**Issue by JJQ7** [ethz-asl/rio#9]
Hi @rikba ,

First of all, thank you for providing this excellent resource! I encountered an issue when trying to download the dataset linked in your repository. It seems that the download is not working for me, and I suspect it might be due to regional restrictions as I'm located outside of Europe.

Could you please confirm if there are any geographical restrictions on the download? If so, are there any alternative ways to access the dataset from regions outside Europe? Any help or guidance would be greatly appreciated.

Thank you for your time and support!

**Comment by rikba** [comment]
Hi there, the download links are currently down. I ll fix them in a moment

**Comment by rikba** [comment]
I updated the links. Thanks for letting me know. I will upload bags with onboard footage after the conference proceedings have been published.
